# Generated by Django 5.0.3 on 2024-03-14 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('profile_pic', models.ImageField(default='Employee/Profilepic/profile.png', upload_to='Employee/Profilepic', verbose_name='Profile Pic')),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile Number')),
                ('email', models.CharField(blank=True, max_length=225, null=True, verbose_name='Email ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, verbose_name='Gender')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('salary', models.CharField(blank=True, max_length=20, null=True, verbose_name='Salary Package')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.department', verbose_name='Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='Present Status')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employeedetail')),
            ],
        ),
    ]
