# Generated by Django 5.0.3 on 2024-03-14 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='joining_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Joining Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='leaving_date',
            field=models.DateField(blank=True, null=True, verbose_name='Leaving Date'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
