# Generated by Django 5.0.3 on 2024-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employeedetail_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='emp_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
