# Generated by Django 5.0.3 on 2024-03-14 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_employeedetail_emp_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='emp_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
