# Generated by Django 5.0.3 on 2024-03-15 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_alter_employeedetail_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='in_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='In Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='out_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Out Time'),
            preserve_default=False,
        ),
    ]
